function initJp() {
    // Get the input element by ID
    const inputElement = e;

    // Set the placeholder text
    inputElement.setAttribute("placeholder", "素早い茶色のキツネが怠惰な犬を飛び越える。");

    // Find the footer element
    const footerElement = document.getElementById("footer");

    // Create buttons for Arabic diacritics
    const diacritics = [
        { char: "〜", title: "波ダッシュ nami dasshu" },
        { char: "・", title: "中黒 nakaguro" },
        { char: "ー", title: "長音符 chōonpu" },
        { char: "「", title: "鉤括弧 kagikakko" },
        { char: "」", title: "鉤括弧 kagikakko" },
        { char: "、", title: "読点 tōten" },
        { char: "。", title: "句点 kuten" },
        { char: "々", title: "踊り字 odoriji - repetition mark kanji" },
        { char: "ー", title: "長音符 chōonpu - katakana long sound symbol" },
        { char: "ヽ", title: "iteration mark katakana" },
        { char: "ヾ", title: "iteration mark katakana with dakuten" },
        { char: "ゝ", title: "iteration mark hiragana" },
        { char: "ゞ", title: "iteration mark hiragana with dakuten" },
    ];

    // Build the button HTML dynamically using a loop
    let buttonHtml = "";
    for (const diacritic of diacritics) {
        buttonHtml += `
        <input type="button" onclick="kb('${diacritic.char}')" value="${diacritic.char}" title="${diacritic.title}">
        `;
    }

    // Set the footer content
    footerElement.innerHTML = buttonHtml;
  
    // Append the footer to the document body
    document.body.appendChild(footerElement);
  
    // Set the page title
    document.title = "Japanese!!";
}


function tojp(car) {
    // Define a map for character replacements
    const charMap = {

        "[ôō]": "oう",
        "[ūû]": "uう",
        "[âā]": "aあ",
        "[îī]": "iい",
        "[êē]": "eい",

        "n": "ん",
        "q": "っ",
        "tsu": "つ",
        "dzu": "づ",
        "dji": "ぢ",
        "kya": "きゃ",
        "kyu": "きゅ",
        "kyo": "きょ",
        "んya": "にゃ",
        "んyu": "にゅ",
        "んyo": "にょ",
        "sha": "しゃ",
        "shi": "し",
        "shu": "しゅ",
        "sho": "しょ",
        "chi": "ち",
        "cha": "ちゃ",
        "chu": "ちゅ",
        "cho": "ちょ",
        "hya": "ひゃ",
        "hyu": "ひゅ",
        "hyo": "ひょ",
        "mya": "みゃ",
        "myu": "みゅ",
        "myo": "みょ",
        "rya": "りゃ",
        "ryu": "りゅ",
        "ryo": "りょ",
        "gya": "ぎゃ",
        "gyu": "ぎゅ",
        "gyo": "ぎょ",
        "bya": "びゃ",
        "byu": "びゅ",
        "byo": "びょ",
        "pya": "ぴゃ",
        "pyu": "ぴゅ",
        "pyo": "ぴょ",
        "ja": "じゃ",
        "ju": "じゅ",
        "jo": "じょ",
        "ba": "ば",
        "da": "だ",
        "ga": "が",
        "ha": "は",
        "ka": "か",
        "ma": "ま",
        "んa": "な",
        "pa": "ぱ",
        "ra": "ら",
        "sa": "さ",
        "ta": "た",
        "wa": "わ",
        "ya": "や",
        "za": "ざ",
        "be": "べ",
        "de": "で",
        "ge": "げ",
        "he": "へ",
        "ke": "け",
        "me": "め",
        "んe": "ね",
        "pe": "ぺ",
        "re": "れ",
        "se": "せ",
        "te": "て",
        "we": "ゑ",
        "ze": "ぜ",
        "bi": "び",
        "gi": "ぎ",
        "hi": "ひ",
        "ki": "き",
        "si": "し",
        "ti": "ち",
        "mi": "み",
        "んi": "に",
        "pi": "ぴ",
        "ri": "り",
        "wi": "ゐ",
        "ji": "じ",
        "zi": "じ",
        "bo": "ぼ",
        "do": "ど",
        "go": "ご",
        "ho": "ほ",
        "ko": "こ",
        "mo": "も",
        "んo": "の",
        "po": "ぽ",
        "ro": "ろ",
        "so": "そ",
        "to": "と",
        "wo": "を",
        "yo": "よ",
        "zo": "ぞ",
        "bu": "ぶ",
        "gu": "ぐ",
        "fu": "ふ",
        "hu": "ふ",
        "ku": "く",
        "mu": "む",
        "んu": "ぬ",
        "pu": "ぷ",
        "ru": "る",
        "su": "す",
        "tu": "つ",
        "yu": "ゆ",
        "zu": "ず",

        // cas des doublons
        "di": "ぢ",
        "じ=": "ぢ",
        "du": "づ",
        "ず=": "づ",

        "a": "あ",
        "[eé]": "え",
        "i": "い",
        "o": "お",
        "u": "う",
        "v": "ゔ",

        "つ=": "っ",
        "あ=": "ぁ",
        "い=": "ぃ",
        "う=": "ぅ",
        "え=": "ぇ",
        "お=": "ぉ",
        "や=": "ゃ",
        "ゆ=": "ゅ",
        "よ=": "ょ",

        //kata
        "[ÔŌ]": "Oー",
        "[ŪÛ]": "Uー",
        "[ÂĀ]": "Aー",
        "[ÎĪ]": "Iー",
        "[ÊĒ]": "Eー",
        "_": "ー",

        "N": "ン",
        "V": "ヴ",
        "Q": "ッ",
        "KYA": "キャ",
        "KYU": "キュ",
        "KYO": "キョ",
        "ンYA": "ニャ",
        "ンYU": "ニュ",
        "ンYO": "ニョ",
        "SHA": "シャ",
        "SHU": "シュ",
        "SHO": "ショ",
        "CHA": "チャ",
        "CHU": "チュ",
        "CHO": "チョ",
        "HYA": "ヒャ",
        "HYU": "ヒュ",
        "HYO": "ヒョ",
        "MYA": "ミャ",
        "MYU": "ミュ",
        "MYO": "ミョ",
        "RYA": "リャ",
        "RYU": "リュ",
        "RYO": "リョ",
        "GYA": "ギャ",
        "GYU": "ギュ",
        "GYO": "ギョ",
        "BYA": "ビャ",
        "BYU": "ビュ",
        "BYO": "ビョ",
        "PYA": "ピャ",
        "PYU": "ピュ",
        "PYO": "ピョ",
        "JA": "ジャ",
        "JU": "ジュ",
        "JO": "ジョ",

        "TSU": "ツ",
        "DZU": "ヅ",
        "DJU": "ヅ",
        "DJI": "ヂ",
        "SHI": "シ",
        "CHI": "チ",

        // supplements
        "JE": "ジェ",
        "TI": "ティ",
        "TU": "トゥ",
        "TYU": "テュ",
        "DI": "ディ",
        "DU": "ドゥ",
        "DYU": "デュ",
        "SI": "スィ",
        "ZI": "ズィ",
        "SHE": "ジェ",
        "CHE": "チェ",
        "TSA": "ツァ",
        "TSI": "ツィ",
        "TSE": "ツェ",
        "TSO": "ツォ",
        "FA": "ファ",
        "FI": "フィ",
        "FE": "フェ",
        "FO": "フォ",
        "FYU": "フュ",
        "HU": "ホゥ",
        "YE": "イェ",
        "YI": "イィ",
        "WU": "ウゥ",



        "BA": "バ",
        "DA": "ダ",
        "GA": "ガ",
        "HA": "ハ",
        "KA": "カ",
        "MA": "マ",
        "ンA": "ナ",
        "PA": "パ",
        "RA": "ラ",
        "SA": "サ",
        "TA": "タ",
        "WA": "ワ",
        "YA": "ヤ",
        "ZA": "ザ",
        "BE": "ベ",
        "DE": "デ",
        "GE": "ゲ",
        "HE": "ヘ",
        "KE": "ケ",
        "ME": "メ",
        "ンE": "ネ",
        "PE": "ペ",
        "RE": "レ",
        "SE": "セ",
        "TE": "テ",
        "WE": "ヱ",
        "ZE": "ゼ",
        "BI": "ビ",
        "GI": "ギ",
        "HI": "ヒ",
        "KI": "キ",
        "MI": "ミ",
        "ンI": "ニ",
        "PI": "ピ",
        "RI": "リ",
        "WI": "ヰ",
        "JI": "ジ",
        "BO": "ボ",
        "DO": "ド",
        "GO": "ゴ",
        "HO": "ホ",
        "KO": "コ",
        "MO": "モ",
        "ンO": "ノ",
        "PO": "ポ",
        "RO": "ロ",
        "SO": "ソ",
        "TO": "ト",
        "WO": "ヲ",
        "YO": "ヨ",
        "ZO": "ゾ",
        "BU": "ブ",
        "GU": "グ",
        "FU": "フ",
        "KU": "ク",
        "MU": "ム",
        "ンU": "ヌ",
        "PU": "プ",
        "RU": "ル",
        "SU": "ス",
        "YU": "ユ",
        "ZU": "ズ",


        //archaic
        //"YE": "𛄡",
        //"YI": "𛄠",
        //"WU": "𛄢",

        "A": "ア",
        "[EÉ]": "エ",
        "I": "イ",
        "O": "オ",
        "U": "ウ",

        "ア=": "ァ",
        "イ=": "ィ",
        "ウ=": "ゥ",
        "エ=": "ェ",
        "オ=": "ォ",
        "ツ=": "ッ",
        "ヤ=": "ャ",
        "ユ=": "ュ",
        "ヨ=": "ョ",

        // 2e série
        "ク=": "ㇰ",
        "シ=": "ㇱ",
        "ス=": "ㇲ",
        "ト=": "ㇳ",
        "ヌ=": "ㇴ",
        "ハ=": "ㇵ",
        "ヒ=": "ㇶ",
        "フ=": "ㇷ",
        "ヘ=": "ㇸ",
        "ホ=": "ㇹ",
        "ム=": "ㇺ",
        "ラ=": "ㇻ",
        "リ=": "ㇼ",
        "ル=": "ㇽ",
        "レ=": "ㇾ",
        "ロ=": "ㇿ",

        "\.": "。",
        "\,": "、",
        "\!": "！",
        "\?": "？",
        "\:": "：",
        "\(": "（",
        "\)": "）",
        "\[": "［",
        "\]": "］",
        "\«": "「",
        "\»": "」",
    }

    // Replace characters using the map
    let convertedText = text.split("").map((char) => charMap[char] || char).join("");
    
    return convertedText;
}
